Dimensione thumbnail ImgBly dinamicizzata - scorporato trailer url - Aggiornamento README
c137ricksanchez/automatic-releaser pull request #9
Opened 2023-10-05 15:27 UTC by AlbyGNinja

* dimensione thumbnail resa dinamica per ImgBly tramite variabile impostabile dall'utente dal keys.json appena sotto il booleano ImgBly ho aggiunto la variabile imgbly_thumb_size con il default a 960 ma ovviamente modificabile dall'utente
* ho scorporato il trailer dal bbcode e aggiornato il template.txt in modo da avere [bbvideo]$TRAILER[/bbvideo] così che uno se lo può personalizzare come vuole
* aggiornato il readme di conseguenza (per la parte della thumb size)

2023-10-10 13:44 UTC, AlbyGNinja commented
Aggiornata la PR con gli ultimi commit per la resa dinamica della chiusura automatica dell'applicazione.

2023-11-10 09:08 UTC, AlbyGNinja commented
Sto facendo le modifiche
Nessun problema per i vari punti, l'unica è la parte dell'exit, adesso comunque si chiude da sola l'app di default essendo appunto la variabile iniziale in `false` l'app si chiude automaticamente, se non dispiace questo lo lascerei

2023-11-10 11:48 UTC, Norman2034 requested changes

2023-11-10 11:48 UTC, Norman2034 commented on config_example/keys.json
> +	"automatic_exit": false
Queste due opzioni sono da rimuovere.
- `imgbly_thumb_size` vale solo per Imgbly, e visto che non è possibile impostare la larghezza delle thumbnails per gli altri due hosting, tanto vale toglierla (anche perché Imgbly viene usato principalmente come ripiego in caso di errori/sforamento della dimensione delle immagini, quindi ha poco senso).
- `automatic_exit` è inutile e riguarda solo la GUI, se il releaser vuole chiudere la finestra al termine del processo può farlo benissimo manualmente. Al massimo si può aggiungere un checkbox da selezionare ogni volta, ma un'opzione nel file `keys.json` no...

2023-11-11 10:15 UTC, Norman2034 approved these changes

2023-11-11 10:23 UTC, merged